### ISSUE TITLE
Depleted Crystals not functional

### ISSUE THREAD

**Issue by DeadLiner** [kihira/PlayerBeacons#2]
Putting depleted crystals into pylons doesn't decrease the corruption buildup, doesn't decrease gained buffs and using any crystal on the beacon does also not do anything, besides the chat message. But I'm not really sure what releasing the corruption actually should do.

Using Forge 10.13.0.1187 (latest), Player Beacons 1.7.10-2.0.0_exp2 and FoxLib 0.2.0

**Comment by kihira** [comment]
Depleted crystals in pylons don't do anything, they're more "dead" crystals and can be re-crafted back into full ones. 
As for the not releasing corruption when used on the beacon, I'll take a look into it

**Comment by kihira** [comment]
Fixed
