### ISSUE TITLE
Beacons fail to re-form

### ISSUE THREAD

**Issue by RiskyKen** [kihira/PlayerBeacons#4]
Removing any Defiled Soul Conductor or Defiled Soul Pylon will stop the beacon from functioning. However replacing it will not reinitialise the beacon.

Replacing the main beacon block seems to reinitialise the beacon properly.

forge-1.7.10-10.13.0.1186
PlayerBeacons-1.7.10-2.0.0_exp2
FoxLib-1.7.10-0.2.0

**Comment by kihira** [comment]
Fixed in 52b709e066476bdd40acea45fd55dbafaf87d39c
