### ISSUE TITLE
Beacon Overlay

### ISSUE THREAD

**Issue by DeadLiner** [kihira/PlayerBeacons#5]
The display (owner/corruption level) when you look at the beacon doesn't work. So there is no way of telling how much corruption the player has accumulated besides using F3/debug screen.
Not sure if this is already implemented again already, so sorry if I'm just uninformed >.<

Forge 10.13.0.1187
FoxLib 0.2.0
PlayerBeacons 1.7.10-2.0.0_exp2

**Comment by kihira** [comment]
Corruption is no longer shown when looking at the beacon. Instead, there are other tells for the corruption level (such as the screen getting darker as well as various negative effects).

However the not showing player name is a bug.
