### ISSUE TITLE
Beacons sometimes not applying buffs

### ISSUE THREAD

**Issue by RiskyKen** [kihira/PlayerBeacons#7]
Beacons sometimes don't reapply buffs. At times the player can be without buffs for around 20 seconds.

Note: Tested in exp3 and exp2 the issues appears to be worse in exp3. May also be worse with larger beacons. (unsure) 

forge-1.7.10-10.13.0.1186
PlayerBeacons-1.7.10-2.0.0_exp3 & PlayerBeacons-1.7.10-2.0.0_exp2
FoxLib-1.7.10-0.2.0

**Comment by kihira** [comment]
Unable to reproduce
